USB_VID = 0x2E8A
USB_PID = 0x101E
USB_PRODUCT = "Zero W"
USB_MANUFACTURER = "Raspberry Pi"

CHIP_VARIANT = "bcm2835"

CIRCUITPY_BUILD_EXTENSIONS = disk.img.zip,kernel.img

CIRCUITPY_ENABLE_MPY_NATIVE = 1
MICROPY_ENABLE_DYNRUNTIME = 1
