USB_VID = 0x239A
USB_PID = 0x802C
USB_PRODUCT = "ItsyBitsy M4 Express"
USB_MANUFACTURER = "Adafruit Industries LLC"

CHIP_VARIANT = SAMD51G19A
CHIP_FAMILY = samd51

QSPI_FLASH_FILESYSTEM = 1
EXTERNAL_FLASH_DEVICES = GD25Q16C
LONGINT_IMPL = MPZ

# No I2S on SAMD51G
CIRCUITPY_AUDIOBUSIO = 0
CIRCUITPY_FLOPPYIO = 0
CIRCUITPY_GIFIO = 0

CIRCUITPY_BITBANG_APA102 = 1

# To me, native code more useful than GIF and BLE
CIRCUITPY_ENABLE_MPY_NATIVE = 1
CIRCUITPY_GIFIO = 0
CIRCUITPY_BLEIO_HCI = 0
MICROPY_ENABLE_DYNRUNTIME = 1
